language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing to be installed"

before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-frontend:local josoa/udagram-frontend:local
  - docker tag udagram-api-feed josoa/udagram-api-feed
  - docker tag udagram-api-user josoa/udagram-api-user
  - docker tag reverseproxy josoa/reverseproxy
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push josoa/udagram-frontend:local
  - docker push josoa/udagram-api-feed:latest
  - docker push josoa/udagram-api-user:latest
  - docker push josoa/reverseproxy:latest