apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-secret
data:
  credentials:  |
    FwoGZXIvYXdzEAEaDGtqL7o8ek8ipsD/4CLVAY+hZ5NHjKIyaESJl5kuxiq+lnhC0+4iwvlS3x/ORsD2zRycfzOwaTLNGKr1r5//yI7pIqIsI3JMJPnfbS32fEGTcgCZvByIRLE85uSioMbOXNHe6S8cC1vAXvjpnEiyBinfQlQv/rnBpCEvUnBMQd+/7kQ1anMJ/iL3jm1hZRB5Ii5GQcpfUH8egA0DVDcci+/nyQNDACGlQon88nDNRnt/n3M2dkUxtMXJi8818EsoFangucJyiWuBNPW9BvnOXT70O6a5nuHO3bXZpmTCkQf/RAmYTCj4oaSaBjItq5zYhNq+rd19Vh1Jp/vlNBM7KidOo0HLNBTVBU+XigjcNgmXmriBhDpa+K+B
