version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
