apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  labels:
    app: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name: feed
        image: josoa/udagram-api-feed
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        envFrom:
        - configMapRef:
            name: env-config-map
        - secretRef:
            name: env-pg-secrets
        volumeMounts:
        - mountPath: "/root/.aws/"
          name: aws-secret

      volumes:
      - name: aws-secret
        configMap:
          name: aws-secret


