name: app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f docker-compose-build.yaml build --parallel
    - name: tag docker image-front
      run: docker tag udagram-frontend:local josoa/udagram-frontend:local
    - name: push front-end
      run: docker push josoa/udagram-frontend:local
    - name: tag docker api-user
      run: docker tag udagram-api-user josoa/udagram-api-user
    - name: Push-user
      run: docker push josoa/udagram-api-user:latest
    - name: tag docker api-feed
      run: docker tag udagram-api-feed josoa/udagram-api-feed
    - name: Push-feed
      run: docker push josoa/udagram-api-feed:latest
    - name: tag docker reverse-proxy
      run: docker tag reverseproxy josoa/reverseproxy
    - name: Push-user
      run: docker push josoa/reverseproxy:latest
